-- Crea la base de datos
CREATE DATABASE BaseDatos;
GO
USE BaseDatos;
GO
-- Tabla PERSONA
CREATE TABLE PERSONA (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(100) NOT NULL,
    Genero VARCHAR(10) NOT NULL,
    Edad INT NOT NULL,
    Identificacion VARCHAR(20) NOT NULL,
    Direccion VARCHAR(200) NOT NULL,
    Telefono VARCHAR(20) NOT NULL
);
GO
-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    ClienteId INT PRIMARY KEY IDENTITY(1,1),
    Contraseña VARCHAR(100) NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    PersonaId INT NOT NULL FOREIGN KEY REFERENCES PERSONA(Id)
);
GO
-- Tabla CUENTA
CREATE TABLE CUENTA (
    CuentaId INT PRIMARY KEY IDENTITY(1,1),
    NumeroCuenta VARCHAR(50) NOT NULL,
    TipoCuenta VARCHAR(50) NOT NULL,
    SaldoInicial DECIMAL(10, 2) NOT NULL,
    Estado VARCHAR(20) NOT NULL,
    ClienteId INT NOT NULL FOREIGN KEY REFERENCES CLIENTE(ClienteId)
);
GO
-- Tabla MOVIMIENTOS
CREATE TABLE MOVIMIENTOS (
    MovimientoId INT PRIMARY KEY IDENTITY(1,1),
    Fecha DATETIME NOT NULL,
    TipoMovimiento VARCHAR(20) NOT NULL,
    Valor DECIMAL(10, 2) NOT NULL,
    Saldo DECIMAL(10, 2) NOT NULL,
    CuentaId INT NOT NULL FOREIGN KEY REFERENCES CUENTA(CuentaId)
);
GO
